### ISSUE TITLE
Some questions about Deformed Shifting Module

### ISSUE THREAD

**Issue by shkarupa-alex** [LeapLabTHU/Slide-Transformer#2]
1. Did you use same or separate deformable kernels for K and V? If they are the same, it is impossible to use different projection dimensions for QK and V...
2. Did you sum kernels (static and deformable) or DWConv outputs? Summing kernels looks like a faster solution in terms of FLOPs, but as far as i understand by default re-parameterization means "sum outputs in train, sum kernels in inference".
3. Did you use some constrains like softmax over the deformable kernel to keep outputs normalized?

**Comment by LeapLabTHU** [comment]
Thanks for you questions.
1. Yes, we use same deformable kernels for K and V to save parameters, and find it does not degrade performance. You can also use different kernels for your need, it achieves similar performance as well.
2. Yes, we sum outputs in train and sum kernels in inference. We sum outputs in train to utilize standard implementation of DWConv.
3. It is a good question, we don't use any constrains and find it works well. Maybe adding constrains can make the model work better.
